adjective = input("Plese enter an adjective: ")
noun = input("Please enter a noun: ")
verb = input ("Please enter a verb ending in -ed: ")
print("Your Madlib:")
print ("The", adjective, noun, verb, "on the stupid idiot's face!")